function BarPlot(xvector1, yvector1, D1)
%CREATEFIGURE(xvector1, yvector1, D1)
%  XVECTOR1:  bar xvector
%  YVECTOR1:  bar yvector
%  D1:  errorbar delta vector data

%  Auto-generated by MATLAB on 25-Jan-2018 20:28:02

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create bar
% Create errorbar
errorbar(yvector1,D1,'Marker','.','LineStyle','none','LineWidth',1,...
    'Color',[0 0 0]);

% Create ylabel
ylabel({'Resting Membrane Potential (mV)'});

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',28);
