function SpontFig(filename,time)
%CREATEFIGURE(X1, Y1)


%  Y1:  vector of y data, membrane potential
Y1 = abfload(filename);
%  Auto-generated by MATLAB on 25-Jan-2018 16:42:40
X1 =  linspace(0,120,length(Y1));
% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create ylabel
ylabel('Membrane Potential (mV)');

% Create xlabel
xlabel('Time (s)');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,time);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[-80 30]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',20);
% Create line
annotation(figure1,'line',[0.130790190735695 0.903723887375113],...
    [0.700149425287356 0.701149425287356],'LineStyle','--');

set(gcf,'color','white')
