function [ChannelID,ChannelLabel,WellID,WellLabel,CompoundID,CompoundName,Experiment,DosepM,DoseLabel,Timestamps,MaximumAmplitudepV,MinimumAmplitudepV,PeaktopeakAmplitudepV] = import_csv_mea(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [CHANNELID,CHANNELLABEL,WELLID,WELLLABEL,COMPOUNDID,COMPOUNDNAME,EXPERIMENT,DOSEPM,DOSELABEL,TIMESTAMPS,MAXIMUMAMPLITUDEPV,MINIMUMAMPLITUDEPV,PEAKTOPEAKAMPLITUDEPV]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [CHANNELID,CHANNELLABEL,WELLID,WELLLABEL,COMPOUNDID,COMPOUNDNAME,EXPERIMENT,DOSEPM,DOSELABEL,TIMESTAMPS,MAXIMUMAMPLITUDEPV,MINIMUMAMPLITUDEPV,PEAKTOPEAKAMPLITUDEPV]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [ChannelID,ChannelLabel,WellID,WellLabel,CompoundID,CompoundName,Experiment,DosepM,DoseLabel,Timestamps,MaximumAmplitudepV,MinimumAmplitudepV,PeaktopeakAmplitudepV] = 
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/03/10 08:49:50

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r','n','UTF-8');
% Skip the BOM (Byte Order Mark).
fseek(fileID, 3, 'bof');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,8,10,11,12,13]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,3,4,5,6,8,10,11,12,13]);
rawCellColumns = raw(:, [7,9]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
ChannelID = cell2mat(rawNumericColumns(:, 1));
ChannelLabel = cell2mat(rawNumericColumns(:, 2));
WellID = cell2mat(rawNumericColumns(:, 3));
WellLabel = cell2mat(rawNumericColumns(:, 4));
CompoundID = cell2mat(rawNumericColumns(:, 5));
CompoundName = cell2mat(rawNumericColumns(:, 6));
Experiment = rawCellColumns(:, 1);
DosepM = cell2mat(rawNumericColumns(:, 7));
DoseLabel = rawCellColumns(:, 2);
Timestamps = cell2mat(rawNumericColumns(:, 8));
MaximumAmplitudepV = cell2mat(rawNumericColumns(:, 9));
MinimumAmplitudepV = cell2mat(rawNumericColumns(:, 10));
PeaktopeakAmplitudepV = cell2mat(rawNumericColumns(:, 11));


